apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: stack
spec:
  buildImage:
    image: gcr.io/paketo-buildpacks/build:base-cnb
  id: io.buildpacks.stacks.bionic
  runImage:
    image: gcr.io/paketo-buildpacks/run:base-cnb
